version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movie_app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    depends_on:
      - db
    networks:
      - movie-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  web:
    image: nginx:stable-alpine
    container_name: movie_web
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - movie-net

  db:
    image: mysql:8.0
    container_name: movie_db
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movie
      MYSQL_USER: movie_user
      MYSQL_PASSWORD: secret
    networks:
      - movie-net

  composer:
    image: composer:latest
    container_name: movie_composer
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    networks:
      - movie-net

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movie_artisan
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    entrypoint: ["php", "artisan"]
    networks:
      - movie-net

volumes:
  dbdata:

networks:
  movie-net:
    driver: bridge
